"use client";
import { FormEvent, useState } from "react";
import { Bell, Check, Copy, Gift } from "lucide-react";

export function RewardsClient({code,preferences}:{code:string;preferences:{email_enabled:boolean;reminder_7d:boolean;reminder_1d:boolean;route_changes:boolean}}){
 const [message,setMessage]=useState(""); const [prefs,setPrefs]=useState(preferences); const [saving,setSaving]=useState(false);
 const shareUrl=typeof window!=="undefined"?`${window.location.origin}/?ref=${code}`:`https://www.thedoggygang.com/?ref=${code}`;
 const redeem=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const data=new FormData(e.currentTarget);const response=await fetch("/api/referrals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:data.get("code")})});const result=await response.json() as {error?:string};setSaving(false);setMessage(response.ok?"Invitación registrada. Los puntos se activarán al completar tu primera aventura.":result.error??"No pudimos registrar el código.");};
 const savePrefs=async(next:typeof prefs)=>{setPrefs(next);const response=await fetch("/api/notification-preferences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({emailEnabled:next.email_enabled,reminder7d:next.reminder_7d,reminder1d:next.reminder_1d,routeChanges:next.route_changes})});setMessage(response.ok?"Preferencias guardadas.":"No pudimos guardar las preferencias.");};
 return <><section className="referral-card"><Gift/><div><span>TU CÓDIGO PERSONAL</span><strong>{code}</strong><p>Cuando una persona invitada completa su primera aventura, tú recibes 150 puntos y ella 75.</p></div><button type="button" onClick={()=>void navigator.clipboard.writeText(shareUrl).then(()=>setMessage("Enlace copiado."))}><Copy/> COPIAR ENLACE</button></section><form className="redeem-card" onSubmit={redeem}><div><span>¿ALGUIEN TE INVITÓ?</span><strong>Registra su código antes de tu primer hike.</strong></div><input name="code" minLength={6} maxLength={20} required placeholder="CÓDIGO"/><button disabled={saving}>{saving?"GUARDANDO…":"APLICAR CÓDIGO"}</button></form><section className="preference-card"><div><Bell/><span><strong>Recordatorios de aventura</strong><small>Tú decides cuáles recibir por correo.</small></span></div>{[["email_enabled","Correos activados"],["reminder_7d","Una semana antes"],["reminder_1d","Un día antes"],["route_changes","Cambios importantes de ruta"]].map(([key,label])=><button type="button" className={prefs[key as keyof typeof prefs]?"on":""} key={key} onClick={()=>void savePrefs({...prefs,[key]:!prefs[key as keyof typeof prefs]})}><i>{prefs[key as keyof typeof prefs]&&<Check/>}</i>{label}</button>)}</section>{message&&<p className="feature-notice" role="status">{message}</p>}</>;
}
